apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      bb: web
  replicas: 2
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: bb-site
        image: nikolaivaticle/docker-test:1.0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: bb-entrypoint
  namespace: default
spec:
  type: LoadBalancer
  selector:
    bb: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: http